- name: Update OS package caches for Debian
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - security
    - rkhunter
    - clamav
    - webserver

- name: Update OS package caches for CentOS
  dnf:
    update_cache: yes
  when: ansible_facts['os_family'] == 'RedHat'
  tags:
    - security
    - rkhunter
    - clamav
    - webserver

- name: Update OS packages
  package:
    name: '*'
    state: latest
  tags:
    - security
    - rkhunter
    - clamav
    - webserver

# Setup rkhunter
- name: Setup rkhunter
  import_tasks: rkhunter.yml

# Setup clamav for Debian
- name: Setup clamav
  import_tasks: clamav.yml
