---
- name: Update OS package caches for Debian
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - security
    - security-update-os-package-caches
    - rkhunter
    - clamav

- name: Update OS package caches for CentOS
  dnf:
    update_cache: yes
  when: ansible_facts['os_family'] == 'RedHat'
  tags:
    - security
    - security-update-os-package-caches
    - rkhunter
    - clamav

- name: Update OS packages
  package:
    name: '*'
    state: latest
  tags:
    - security
    - security-update-os-packages
    - rkhunter
    - clamav

# Setup rkhunter
- name: Setup rkhunter
  import_tasks: rkhunter.yml
  tags:
    - security
    - rkhunter

# Setup clamav for Debian
- name: Setup clamav
  import_tasks: clamav.yml
  tags:
    - security
    - clamav
