- name: Install OS packages for Debian
  package:
    name:
      - rkhunter
    state: latest
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - security
    - rkhunter
    - webserver

- name: Install OS packages for CentOS
  package:
    name:
      - rkhunter
  when: ansible_facts['os_family'] == 'RedHat'
  tags:
    - security
    - rkhunter
    - webserver

- name: Copy rkhunter config
  copy:
    src: "../files/{{ ansible_facts['os_family'] }}/etc/{{ item }}"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: 0644
  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'RedHat'
  with_items:
     - rkhunter.conf
  tags:
    - security
    - rkhunter
    - webserver

# Reference: https://github.com/maxlareo/ansible-rkhunter
# When first time to run, it is always failed.
# So use failed_when and changed_when condition.
- name: Update rkhunter
  command: rkhunter --update
  register: rkhunter_update_result
  failed_when: (not rkhunter_update_result.rc == 2) and (not rkhunter_update_result.rc == 0)
  changed_when: false
  tags:
    - security
    - rkhunter
    - webserver

# Caution: it should run after ensure that all warning repoted by rkhunter are safe.
- name: Propupd rkhunter
  command: rkhunter --propupd
  when: rkhunter.propupd | default(false)
  tags:
    - security
    - rkhunter
    - webserver

- name: Check warnings after updated rkhunter config
  command: rkhunter --check --skip-keypress --report-warnings-only
  register: rkhunter_check_result
  tags:
    - security
    - rkhunter
    - webserver

- name: Check rkhunter stdout
  fail:
    msg: rkhunter reported some warning...
  when: not rkhunter_check_result.stdout == ""
  tags:
    - security
    - rkhunter
    - webserver

- name: Config rkhunter daily job for Debian
  template:
    src: "{{ ansible_facts['os_family'] }}/etc/default/{{ item }}.j2"
    dest: "/etc/default/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
     - rkhunter
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - security
    - rkhunter
    - webserver

- name: Config rkhunter daily job for CentOS
  template:
    src: "{{ ansible_facts['os_family'] }}/etc/sysconfig/{{ item }}.j2"
    dest: "/etc/sysconfig/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
     - rkhunter
  when: ansible_facts['os_family'] == 'RedHat'
  tags:
    - security
    - rkhunter
    - webserver
